---
title: "NisaProject"
author: "Mich Stg"
date: "9/3/2021"
output: html_document
---

```{r setup}
#TABEL MORTALITA
tabel.mortalita <- function(x,qx,y){
  px <- 1-qx
  lx <- NULL
  for (i in 2:length(x)) {
    lx[1] <- 100000
    lx[i] <- lx[i-1]*px[i-1]
  }
  dx=sx=ex <- NULL
  for(i in 1:length(x)){
    dx[i] <- lx[i]*qx[i]
    sx[1] <- 1
    sx[i] <- lx[i+1]/lx[i]
    sx[length(x)] <- 0
    ex[length(x)] <- 0
    ex[length(x)-i] <- px[length(x)-i]+
      (px[length(x)-i]*ex[length(x)-i+1])
  }
  tabel <- data.frame(age=x,px=px,lx=lx,qx=qx,sx=sx,ex=ex)
  print(tabel,digits = 3)
}

#input age,qx,qy tabel mortalita 2011
age = tmi_2011$x[1:112]
male = tmi_2011$qx[1:112]
female = tmi_2011$qy[1:112]

qxmale=tabel.mortalita(age,male,100000)
qxfemale=tabel.mortalita(age,female,100000)
```

```{r Male}
#TABEL MALE
library(dplyr)

vx = c()
dx = c()
Cx = c()

for(i in 0:111){
  vx[i] <- ((1+0.05)^(-1))^i
  dx[i] <- qxmale$lx[i]-qxmale$lx[i+1]
  Cx[i] <- vx[i] * dx[i]
}

n <- append(1,vx)
qxmale$vx <- n
n2 <- append(dx,qxmale$lx[112])
qxmale$dx <- n2
n3 <- append(Cx,0)
qxmale$Cx <- n3
qxmale <- qxmale %>% mutate(Dx = qxmale$vx * qxmale$lx)

Nx = c()
Sx = c()
Mx = c()

for(i in 1:nrow(qxmale)){
  sums <- qxmale$Dx[i:nrow(qxmale)]
  Nx[i] <- sum(sums)
  
  sums2 <- Nx[i:nrow(qxmale)]
  Sx[i] <- sum(sums2)
  
  sums3 <- qxmale$Cx[i:nrow(qxmale)]
  Mx[i]<- sum(sums3)
}

qxmale$Sx <- Sx
qxmale$Nx <- Nx
qxmale$Mx <- Mx
View(qxmale)
```

```{r Female}
library(dplyr)
#TABEL FEMALE
vy = c()
dy = c()
Cy = c()

for(i in 0:111){
  vy <- qxmale$vx 
  dy[i] <- qxfemale$lx[i]-qxfemale$lx[i+1]
  Cy[i] <- vy[i+1] * dy[i]
}

qxfemale$vy <- vy
n <- append(dy,qxfemale$lx[112])
qxfemale$dy <- n
n2 <- append(Cy,0)
qxfemale$Cy <- n2
qxfemale <- qxfemale %>% mutate(Dy = qxfemale$vy * qxfemale$lx)

Ny = c()
Sy = c()
My = c()

for(i in 0:nrow(qxfemale)){
  sums <- qxfemale$Dy[i:nrow(qxfemale)]
  Ny[i] <- sum(sums)
  
  sums2 <- Ny[i:nrow(qxfemale)]
  Sy[i] <- sum(sums2)
  
  sums3 <- qxfemale$Cy[i:nrow(qxfemale)]
  My[i] <- sum(sums3)
}

qxfemale$Ny <- Ny
qxfemale$Sy <- Sy
qxfemale$My <- My
View(qxfemale)

qxfemale$lx[32]
```

```{r}
# TABEL JOINTLIFE
pxy = c()
qxy = c()
lxy = c()
dxy = c()
vxy = c()
Dxy = c()
Cxy = c()
Nxy = c()
Mxy = c()

n = 23
for (i in 1:n) {
  pxy[i] <- qxmale$px[35+i]*qxfemale$px[31+i]
  qxy[i] <- 1-pxy[i]
  lxy[i] <- qxmale$lx[35+i]*qxfemale$lx[31+i]
  dxy[i] <- lxy[i] - lxy[i+1]
  vxy[i] <- ((1+0.05)^(-1))^((qxmale$age[35+i]+qxfemale$age[31+i])/2+1)
}

dxy[23] <- lxy[23]

for (i in 1:n) {
  Dxy[i] <- vxy[i] * lxy[i]
  Cxy[i] <- dxy[i] * vxy[i]
  
  sums <- Dxy[i:n]
  Nxy[i] <- sum(sums)
  
  sums2 = Cxy[i:n]
  Mxy[i] <- sum(sums2)
}

jointlife= data.frame(pxy,qxy,lxy,dxy,vxy,Dxy,Cxy,Nxy,Mxy)

View(jointlife)

```

```{r}
#ANUITAS AWAL MALE & FEMALE
anuitasawal_lk <- function(umur,jangka){
  anuitasawal <- ((qxmale$Nx[umur+1]-qxmale$Nx[umur+jangka+1])/
                  (qxmale$Dx[umur+1]))
  cat("anuitas awal =",anuitasawal,"\n")
}

anuitasawal_pr <- function(umur,jangka){
  anuitasawal <- ((qxfemale$Ny[umur+1]-qxfemale$Ny[umur+jangka+1])/
                  (qxfemale$Dy[umur+1]))
  cat("anuitas awal =",anuitasawal,"\n")
}

anuitasawal_lk(umur=35,jangka=22)
anuitasawal_pr(umur=31,jangka=22)

#ANUITAS AWAL JOIN LIFE
Nxy <- function(pria,wanita){
  if(pria==35 & wanita ==31){jointlife$Nxy[1]}
  else if(pria==36 & wanita ==32){jointlife$Nxy[2]}
  else if(pria==37 & wanita ==33){jointlife$Nxy[3]}
  else if(pria==38 & wanita ==34){jointlife$Nxy[4]}
  else if(pria==39 & wanita ==35){jointlife$Nxy[5]}
  else if(pria==40 & wanita ==36){jointlife$Nxy[6]}
  else if(pria==41 & wanita ==37){jointlife$Nxy[7]}
  else if(pria==42 & wanita ==38){jointlife$Nxy[8]}
  else if(pria==43 & wanita ==39){jointlife$Nxy[9]}
  else if(pria==44 & wanita ==40){jointlife$Nxy[10]}
  else if(pria==45 & wanita ==41){jointlife$Nxy[11]}
  else if(pria==46 & wanita ==42){jointlife$Nxy[12]}
  else if(pria==47 & wanita ==43){jointlife$Nxy[13]}
  else if(pria==48 & wanita ==44){jointlife$Nxy[14]}
  else if(pria==49 & wanita ==45){jointlife$Nxy[15]}
  else if(pria==50 & wanita ==46){jointlife$Nxy[16]}
  else if(pria==51 & wanita ==47){jointlife$Nxy[17]}
  else if(pria==52 & wanita ==48){jointlife$Nxy[18]}
  else if(pria==53 & wanita ==49){jointlife$Nxy[19]}
  else if(pria==54 & wanita ==50){jointlife$Nxy[20]}
  else if(pria==55 & wanita ==51){jointlife$Nxy[21]}
  else if(pria==56 & wanita ==52){jointlife$Nxy[22]}
  else if(pria==57 & wanita ==53){jointlife$Nxy[23]}
  else{0}
}

Dxy <- function(pria,wanita){
  if(pria==35 & wanita ==31){jointlife$Dxy[1]}
  else if(pria==36 & wanita ==32){jointlife$Dxy[2]}
  else if(pria==37 & wanita ==33){jointlife$Dxy[3]}
  else if(pria==38 & wanita ==34){jointlife$Dxy[4]}
  else if(pria==39 & wanita ==35){jointlife$Dxy[5]}
  else if(pria==40 & wanita ==36){jointlife$Dxy[6]}
  else if(pria==41 & wanita ==37){jointlife$Dxy[7]}
  else if(pria==42 & wanita ==38){jointlife$Dxy[8]}
  else if(pria==43 & wanita ==39){jointlife$Dxy[9]}
  else if(pria==44 & wanita ==40){jointlife$Dxy[10]}
  else if(pria==45 & wanita ==41){jointlife$Dxy[11]}
  else if(pria==46 & wanita ==42){jointlife$Dxy[12]}
  else if(pria==47 & wanita ==43){jointlife$Dxy[13]}
  else if(pria==48 & wanita ==44){jointlife$Dxy[14]}
  else if(pria==49 & wanita ==45){jointlife$Dxy[15]}
  else if(pria==50 & wanita ==46){jointlife$Dxy[16]}
  else if(pria==51 & wanita ==47){jointlife$Dxy[17]}
  else if(pria==52 & wanita ==48){jointlife$Dxy[18]}
  else if(pria==53 & wanita ==49){jointlife$Dxy[19]}
  else if(pria==54 & wanita ==50){jointlife$Dxy[20]}
  else if(pria==55 & wanita ==51){jointlife$Dxy[21]}
  else if(pria==56 & wanita ==52){jointlife$Dxy[22]}
  else if(pria==57 & wanita ==53){jointlife$Dxy[23]}
  else{0}
}

anuitasjointlife <- function(pria,wanita,jangka){
  anuitas <- (Nxy(pria,wanita)-Nxy(pria+jangka,wanita+jangka))/Dxy(pria,wanita)
  return(anuitas)
}

anuitasjointlife(pria = 35,wanita = 31,jangka = 22)

```

```{r}
#NILAI PREMI TUNGGAL
Mxy <- function(pria,wanita){
  if(pria==35 & wanita ==31){jointlife$Mxy[1]}
  else if(pria==36 & wanita ==32){jointlife$Mxy[2]}
  else if(pria==37 & wanita ==33){jointlife$Mxy[3]}
  else if(pria==38 & wanita ==34){jointlife$Mxy[4]}
  else if(pria==39 & wanita ==35){jointlife$Mxy[5]}
  else if(pria==40 & wanita ==36){jointlife$Mxy[6]}
  else if(pria==41 & wanita ==37){jointlife$Mxy[7]}
  else if(pria==42 & wanita ==38){jointlife$Mxy[8]}
  else if(pria==43 & wanita ==39){jointlife$Mxy[9]}
  else if(pria==44 & wanita ==40){jointlife$Mxy[10]}
  else if(pria==45 & wanita ==41){jointlife$Mxy[11]}
  else if(pria==46 & wanita ==42){jointlife$Mxy[12]}
  else if(pria==47 & wanita ==43){jointlife$Mxy[13]}
  else if(pria==48 & wanita ==44){jointlife$Mxy[14]}
  else if(pria==49 & wanita ==45){jointlife$Mxy[15]}
  else if(pria==50 & wanita ==46){jointlife$Mxy[16]}
  else if(pria==51 & wanita ==47){jointlife$Mxy[17]}
  else if(pria==52 & wanita ==48){jointlife$Mxy[18]}
  else if(pria==53 & wanita ==49){jointlife$Mxy[19]}
  else if(pria==54 & wanita ==50){jointlife$Mxy[20]}
  else if(pria==55 & wanita ==51){jointlife$Mxy[21]}
  else if(pria==56 & wanita ==52){jointlife$Mxy[22]}
  else if(pria==57 & wanita ==53){jointlife$Mxy[23]}
  else{0}
}

premitunggal <- function(pria,wanita,jangka){
  premitgl <- (Mxy(pria,wanita)-Mxy(pria+jangka,wanita+jangka))/Dxy(pria,wanita)
  return(premitgl)
}

premitunggal(pria = 35,wanita = 31,jangka = 22)

#NILAI PREMI BERSIH TAHUNAN
premibersih <- function(pria,wanita,jangka,R=100000000){
  x <- premitunggal(pria,wanita,jangka)
  y <- anuitasjointlife(pria,wanita,jangka)
  premithn <- (x/y)*R
  return(premithn)
}

premibersih(pria = 35,wanita = 31,jangka = 22)
```

```{r}
#Metode Illonois
komisi = 0.05
R = 100000000

betaIllinois <- ((premibersih(pria= 35,wanita= 31,jangka= 22)*anuitasjointlife(35,31,20))+ komisi)/(anuitasjointlife(35,31,19)+1)

alfaIllinois <- betaIllinois - komisi
VIllinois = c()

for (t in 1:22) {
  pria = 35
  wanita = 31
  jangka = 22
  VIllinois[t] <- (R*premitunggal(pria+t,wanita+t,jangka-t))-
    ((betaIllonis-premibersih(pria,wanita,jangka)))*
    anuitasjointlife(pria+t,wanita+t,jangka-t)
  
  print(VIllinois[t])
}

```

```{r}
#Metode Canadian
Cxy <- function(pria,wanita){
  if(pria==35 & wanita ==31){jointlife$Cxy[1]}
  else if(pria==36 & wanita ==32){jointlife$Cxy[2]}
  else if(pria==37 & wanita ==33){jointlife$Cxy[3]}
  else if(pria==38 & wanita ==34){jointlife$Cxy[4]}
  else if(pria==39 & wanita ==35){jointlife$Cxy[5]}
  else if(pria==40 & wanita ==36){jointlife$Cxy[6]}
  else if(pria==41 & wanita ==37){jointlife$Cxy[7]}
  else if(pria==42 & wanita ==38){jointlife$Cxy[8]}
  else if(pria==43 & wanita ==39){jointlife$Cxy[9]}
  else if(pria==44 & wanita ==40){jointlife$Cxy[10]}
  else if(pria==45 & wanita ==41){jointlife$Cxy[11]}
  else if(pria==46 & wanita ==42){jointlife$Cxy[12]}
  else if(pria==47 & wanita ==43){jointlife$Cxy[13]}
  else if(pria==48 & wanita ==44){jointlife$Cxy[14]}
  else if(pria==49 & wanita ==45){jointlife$Cxy[15]}
  else if(pria==50 & wanita ==46){jointlife$Cxy[16]}
  else if(pria==51 & wanita ==47){jointlife$Cxy[17]}
  else if(pria==52 & wanita ==48){jointlife$Cxy[18]}
  else if(pria==53 & wanita ==49){jointlife$Cxy[19]}
  else if(pria==54 & wanita ==50){jointlife$Cxy[20]}
  else if(pria==55 & wanita ==51){jointlife$Cxy[21]}
  else if(pria==56 & wanita ==52){jointlife$Cxy[22]}
  else if(pria==57 & wanita ==53){jointlife$Cxy[23]}
  else{0}
}

P = 0.99869
alfaCanadian = premibersih(pria= 35,wanita= 31,jangka= 22)*
  (P-(Cxy(pria=35,wanita=31)/Dxy(pria = 35,wanita = 31)))

betaCanadian = premibersih(pria= 35,wanita= 31,jangka= 22)+
  ((P-(Cxy(pria=35,wanita=31)/Dxy(pria = 35,wanita = 31)))/(anuitasjointlife(pria = 35,wanita = 31,jangka = 22)-1))

VCanadian = c()

for (t in 1:22) {
  pria = 35
  wanita = 31
  jangka = 22
  VCanadian[t] <- (R*premitunggal(pria+t,wanita+t,jangka-t))-
    (betaCanadian*anuitasjointlife(pria+t,wanita+t,jangka-t))
  
  print(VCanadian[t])
}

```

```{r}
#Buat Tabel Illinois dan Canadian
TabelKeputusan = data.frame(VIllinois,VCanadian)
View(TabelKeputusan)

library(ggplot2)
library(tidyr)
names(TabelKeputusan)[1] <- "Illinois"
names(TabelKeputusan)[2] <- "Canadian"
TabelKeputusan$Jangka_Tahun = c(1:22)

Tabel <- TabelKeputusan %>% gather(key = "Metode",value = "Jumlah",c(-Jangka_Tahun))

#Buat Plot Illinois dan Canadian
ggplot(Tabel) + geom_line(aes(x=Jangka_Tahun,y=Jumlah,group = Metode,col = Metode))+
  labs(title = "Perbandingan Cadangan Premi Tahunan",subtitle = "Umur Pria = 31 tahun , Umur Wanita = 29 tahun , Jangka Waktu = 22 tahun ")+
  xlab("Tahun ke-1 sampai ke-22")

```
